# Reusable GitHub Actions workflow for building and deploying a website to S3.
#
# Builds the given package, checks lint and formatting, syncs to S3, and
# invalidates the CloudFront distribution.

name: Build and Deploy Frontend

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
      package-path:
        type: string
        required: true
      aws-s3-bucket:
        type: string
        required: true
      aws-cloudfront-distribution:
        type: string
        required: true
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  deploy_frontend:
    name: "Deploy ${{inputs.package-name}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: build
        run: |
          node --version
          pnpm install --frozen-lockfile
          pnpm build --filter="${{ inputs.package-name }}"
      - name: lint
        run: pnpm lint --filter="${{ inputs.package-name }}"
      - name: check format
        run: pnpm format
        continue-on-error: false
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ inputs.aws-s3-bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
          AWS_REGION: "us-west-2"
          SOURCE_DIR: "${{ inputs.package-path }}/out"
      - uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ inputs.aws-cloudfront-distribution }}
          PATHS: "/*"
          AWS_REGION: "us-west-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
